FROM node:20-alpine AS builder

ARG VITE_AUTH_URL
ENV VITE_AUTH_URL=${VITE_AUTH_URL}

ARG VITE_HOUSING_URL
ENV VITE_HOUSING_URL=${VITE_HOUSING_URL}

ARG VITE_PROFILE_URL
ENV VITE_PROFILE_URL=${VITE_PROFILE_URL}

ARG VITE_BUCKET_UPLOAD_URL
ENV VITE_BUCKET_UPLOAD_URL=${VITE_BUCKET_UPLOAD_URL}

ARG VITE_WEALTH_MANAGEMENT_URL
ENV VITE_WEALTH_MANAGEMENT_URL=${VITE_WEALTH_MANAGEMENT_URL}

ARG VITE_DASHBOARD_MANAGEMENT_URL
ENV VITE_DASHBOARD_MANAGEMENT_URL=${VITE_DASHBOARD_MANAGEMENT_URL}

ARG VITE_CALENDAR_URL
ENV VITE_CALENDAR_URL=${VITE_CALENDAR_URL}

ARG VITE_DOCUMENT_URL
ENV VITE_DOCUMENT_URL=${VITE_DOCUMENT_URL}

ARG VITE_ADMIN_URL
ENV VITE_ADMIN_URL=${VITE_ADMIN_URL}

ARG VITE_CHAT_URL
ENV VITE_CHAT_URL=${VITE_CHAT_URL}

WORKDIR /app
RUN apk add --no-cache git

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/build/server ./server
COPY --from=builder /app/package*.json ./


RUN npm install

ENV PORT=8080
EXPOSE 8080

CMD ["node", "server/server.js"]
