// src/rolesPermissions.ts
export const rolesPermissions: Record<string, string[]> = {
  owner: [
    "setHouse",
    "getHouse",
    "updateHouse",
    "deleteHouse",
    "getTenantsByOwner",
    "getTenants",
    "addCaution",
    "updateCaution",
    "deleteCaution",
    "addTenantWithHousing",
    "updateTenantWithHousing",
    "deleteTenantWithHousing",
  ],
  tenant: [],
  everyone: [
    "updateProfile",
    "postDocument",
    "deleteDocument",
    "setProfile",
    "getProfile",
    "deleteProfile",
    "getDocument",
    "getOwners",
    "getOwnersById",
    "getTenantById",
    "getOwnerByTenant",
    "getMessage",
    "sendMessage",
    "createEvent",
    "getEventById",
    "getAllEvents",
    "updateEvent",
    "deleteEvent",
    "getUpcomingEvents",
    "getEventsByCalendar",
    "filterEvents",
    "createSmtpServer",
    "createReminder",
    "createTemplateEmail",
  ],
};
